<style type="text/css">
<!--
.style3 {   font-size: 12px;
    color: #3333CC;
    font-weight: bold;
}
.style1 {   font-size: 12px;
    font-weight: bold;
    color: #FFFFFF;
}
-->
</style>
<table width="100%"  border="0" cellspacing="0" cellpadding="0">
  <tr bgcolor="#666699">
    <td><span class="style1">&nbsp;&nbsp;&nbsp;Entry (Welcome page) </span></td>
  </tr>
  <tr>
    <td width="86%" align="left" valign="top"><table width="100%"  border="0" cellspacing="0" cellpadding="0">
        <tr>
          <td width="76%" align="left" valign="top"><table width="100%"  border="0" cellspacing="6" cellpadding="6">
            <tr>
              <td align="left" valign="top"><p>Welcome to the SMART Framework
                  <strong>test</strong> administration area. You can switch to the public page <a href="<?php echo SF_CONTROLLER; ?>">here</a>.</p>
                <p>This page was generated by the default module. In the top right corner you can
                  select
                  all available modules from the select menu. This release is
                  only for testing purpose to demonstrate how the modules mechanism
                  works.</p>
                <p>&nbsp;</p>
                <p>&nbsp; </p></td>
            </tr>
          </table></td>
        </tr>
    </table></td>
  </tr>
</table>
